import { readFile, writeFile } from 'fs/promises'
import { existsSync } from 'fs'
import { join } from 'path'
import type { ThemeAdapter, ArticleFM, PatchConfigOpts, NavItem } from './types.js'

/**
 * Astro Rocket – https://github.com/hansmartens68/Astro-Rocket
 *
 * Production-ready Astro 6 + Tailwind CSS 4 starter.
 * 57+ components, 12 colour themes, dark mode, i18n, blog, projects, contact.
 *
 * Bundled as a git submodule at bundled-themes/rocket/ — version is pinned
 * to the submodule commit, never downloaded at migration time.
 *
 * Content structure:
 *   src/content/blog/en/<slug>.mdx   blog posts (flat files, locale-subdirected)
 *   public/images/                   media
 */
export const rocketAdapter: ThemeAdapter = {
  id: 'rocket',
  name: 'Astro Rocket',
  repo: 'hansmartens68/Astro-Rocket',
  branch: 'main',
  description: 'Astro 6 + Tailwind CSS 4 — 57+ components, 12 themes, dark mode, i18n, blog',
  bundled: true,

  contentDir: 'src/content/blog/en',
  mediaDir: 'public/images',
  fileExt: 'mdx',
  useDirectoryEntries: false,
  sampleContentDirs: ['src/content/blog'],

  mapFrontmatter(fm: ArticleFM, siteAuthor: string): Record<string, unknown> {
    return {
      title: (fm.seoTitle || fm.title || 'Untitled').slice(0, 100),
      description: (fm.seoDescription || fm.excerpt || '').slice(0, 200),
      publishedAt: fm.publishedAt ? new Date(fm.publishedAt) : new Date(),
      author: fm.author || siteAuthor || 'Team',
      tags: fm.tags ?? [],
      draft: false,
      featured: false,
      locale: 'en',
    }
  },

  async patchConfig(outputDir: string, opts: PatchConfigOpts): Promise<void> {
    // 1. Patch src/config/site.config.ts
    const siteConfigPath = join(outputDir, 'src', 'config', 'site.config.ts')
    if (existsSync(siteConfigPath)) {
      let cfg = await readFile(siteConfigPath, 'utf-8')

      // Replace name: 'Astro Rocket'
      cfg = cfg.replace(
        /(^\s*name\s*:\s*)(['"`])([^'"`\n]*)(\2)/m,
        (_m, key, q, _old, qEnd) => `${key}${q}${opts.siteTitle}${qEnd}`,
      )
      // Replace description (first occurrence — the top-level site description)
      cfg = cfg.replace(
        /(^\s*description\s*:\s*)(['"`])([^'"`\n]*)(\2)/m,
        (_m, key, q, _old, qEnd) => `${key}${q}${opts.siteDescription.slice(0, 200)}${qEnd}`,
      )
      // Replace author: 'Hans Martens'
      cfg = cfg.replace(
        /(^\s*author\s*:\s*)(['"`])([^'"`\n]*)(\2)/m,
        (_m, key, q, _old, qEnd) => `${key}${q}${opts.authorName || opts.siteTitle}${qEnd}`,
      )

      await writeFile(siteConfigPath, cfg, 'utf-8')
    }

    // 2. Rewrite src/config/nav.config.ts with WP navigation
    const navConfigPath = join(outputDir, 'src', 'config', 'nav.config.ts')
    if (existsSync(navConfigPath)) {
      const navContent = `/**
 * Navigation Configuration — generated by depress
 */

export interface NavItem {
  label: string;
  href: string;
  order: number;
}

export const navItems: NavItem[] = [
${serializeRocketNavItems(opts.navItems)}];

export function getNavItems(): NavItem[] {
  return [...navItems].sort((a, b) => a.order - b.order);
}
`
      await writeFile(navConfigPath, navContent, 'utf-8')
    }

    // 3. Patch astro.config.mjs — swap vercel/netlify for node adapter + add Keystatic
    const astroCfgPath = join(outputDir, 'astro.config.mjs')
    if (existsSync(astroCfgPath)) {
      let cfg = await readFile(astroCfgPath, 'utf-8')

      if (!cfg.includes('keystatic')) {
        // Replace vercel/netlify imports + conditional adapter logic with node adapter
        cfg = cfg.replace(
          /import vercel from '@astrojs\/vercel';\nimport netlify from '@astrojs\/netlify';\n\nconst isNetlify = process\.env\.DEPLOY_TARGET === 'netlify';\n/,
          `import node from '@astrojs/node';\nimport keystatic from '@keystatic/astro';\n\n`,
        )
        // Replace adapter: isNetlify ? netlify() : vercel()
        cfg = cfg.replace(
          /adapter: isNetlify \? netlify\(\) : vercel\(\),/,
          `adapter: node({ mode: 'standalone' }),`,
        )
        // Add keystatic() to integrations array
        cfg = cfg.replace(
          /(\bintegrations\s*:\s*\[)/,
          `$1\n    keystatic(),`,
        )
      }

      await writeFile(astroCfgPath, cfg, 'utf-8')
    }

    // 4. Add Keystatic deps to package.json
    const pkgPath = join(outputDir, 'package.json')
    if (existsSync(pkgPath)) {
      const pkg = JSON.parse(await readFile(pkgPath, 'utf-8'))
      if (!pkg.dependencies?.['@keystatic/core']) {
        pkg.dependencies = {
          ...pkg.dependencies,
          '@keystatic/core': '^0.5.0',
          '@keystatic/astro': '^5.0.0',
          '@astrojs/node': '^9.0.0',
        }
        // Remove vercel/netlify adapters (optional — avoid unused deps)
        delete pkg.dependencies?.['@astrojs/vercel']
        delete pkg.dependencies?.['@astrojs/netlify']
        await writeFile(pkgPath, JSON.stringify(pkg, null, 2) + '\n', 'utf-8')
      }
    }

    // 5. Write keystatic.config.ts — flat files, no trailing slash in path
    const keystaticcfgPath = join(outputDir, 'keystatic.config.ts')
    if (!existsSync(keystaticcfgPath)) {
      const keystaticcfg = `import { config, fields, collection } from '@keystatic/core'

export default config({
  storage: {
    kind: 'local',
  },

  collections: {
    posts: collection({
      label: 'Blog Posts',
      slugField: 'title',
      path: 'src/content/blog/en/*',
      format: { contentField: 'content' },
      schema: {
        title: fields.slug({ name: { label: 'Title' } }),
        description: fields.text({ label: 'Description', multiline: true }),
        publishedAt: fields.datetime({ label: 'Published At', defaultValue: { kind: 'now' } }),
        author: fields.text({ label: 'Author', defaultValue: 'Team' }),
        tags: fields.array(fields.text({ label: 'Tag' }), { label: 'Tags', itemLabel: (props) => props.fields.value.value }),
        locale: fields.select({
          label: 'Locale',
          options: [
            { label: 'English', value: 'en' },
            { label: 'Spanish', value: 'es' },
            { label: 'French', value: 'fr' },
          ],
          defaultValue: 'en',
        }),
        draft: fields.checkbox({ label: 'Draft', defaultValue: false }),
        featured: fields.checkbox({ label: 'Featured', defaultValue: false }),
        content: fields.mdx({ label: 'Content' }),
      },
    }),
  },
})
`
      await writeFile(keystaticcfgPath, keystaticcfg, 'utf-8')
    }
  },
}

function serializeRocketNavItems(navItems: NavItem[]): string {
  const items = navItems.length > 0
    ? navItems
    : [{ label: 'Blog', href: '/blog', children: [] }]

  return items.map((item, i) =>
    `  { label: ${JSON.stringify(item.label)}, href: ${JSON.stringify(item.href)}, order: ${i + 1} },\n`
  ).join('')
}
